// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZs8aCZ_PoBo1G9XXaeUSHWvb0GV9sFZ0',
    appId: '1:704301189018:web:7a136a08b261ab57fd5c23',
    messagingSenderId: '704301189018',
    projectId: 'head-stone-revelation',
    authDomain: 'head-stone-revelation.firebaseapp.com',
    storageBucket: 'head-stone-revelation.firebasestorage.app',
    measurementId: 'G-EZR3LGEML3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXTwJtRMZJ3-BVG7wGKlW8SKTtr7Wr0aw',
    appId: '1:704301189018:android:c487acb40f83703afd5c23',
    messagingSenderId: '704301189018',
    projectId: 'head-stone-revelation',
    storageBucket: 'head-stone-revelation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhuqUmYeN5QFzIZDbDk-krYji2tr6Q58I',
    appId: '1:704301189018:ios:e5961b4f6312acf0fd5c23',
    messagingSenderId: '704301189018',
    projectId: 'head-stone-revelation',
    storageBucket: 'head-stone-revelation.firebasestorage.app',
    iosBundleId: 'com.example.lordJesusChristFellowship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZs8aCZ_PoBo1G9XXaeUSHWvb0GV9sFZ0',
    appId: '1:704301189018:web:9946286cd3c4a001fd5c23',
    messagingSenderId: '704301189018',
    projectId: 'head-stone-revelation',
    authDomain: 'head-stone-revelation.firebaseapp.com',
    storageBucket: 'head-stone-revelation.firebasestorage.app',
    measurementId: 'G-90E30CXVN5',
  );
}
